### ISSUE TITLE
Border pins for Lost Treasure not showing anymore on MiniMap by Fyrakin

### ISSUE THREAD

**Issue by Masteroshi430** [simenon/LostTreasure#68]
Hi, since v23 border pins for this addon are not showing anymore on MiniMap by Fyrakin (there's an option to show them),
I am asking here because the other addon had not being updated since and it was working before.
it looks like it uses this to know if the pin is from this addon: 
`if string.sub(string.lower(pin.pinTexture),1,12) == "losttreasure" then`

**Comment by Scootworks** [comment]
The reason why it doesn't work is evident. There is no folder with the icon name "losttreasure" anymore. I wouldn't say I like the idea of Fyrakin's Minimap to check it this way. It's not scaleable for other addons too. I'm happy to add more API functions into LibTreasure to make it work. But instead of checking file paths, it would be sufficient to check the pin names by the ESO API. Afaik they have unique names too.

**Comment by Masteroshi430** [comment]
I solved it on Minimap side :-)
